### ISSUE TITLE
Pressing 'Login' and logging in leads to a 404

### ISSUE THREAD

**Issue by parrotmac** [maryburrito/backtrack#9]
Steps to reproduce:
- Open home page while signed out
- Click 'Login' button in upper right
- Enter valid credentials, and click enter
- Resulting URL (`/accounts/profile/`) shows a 404 error

A simple fix might be to append something like `?next=/` to the URL used by the login button so it goes back to the home screen. Another solution could be to redirect the URL from above to the home page, or even to add a user profile page. Another option could be passing a `success_url` to the [LoginView](https://docs.djangoproject.com/en/3.1/topics/auth/default/#django.contrib.auth.views.LoginView) so that it goes somewhere else after successfully logging in.

**Comment by maryburrito** [comment]
This should work now
